"""empty message

Revision ID: 4ffd3e7d09ee
Revises: 
Create Date: 2025-05-10 19:58:13.728786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffd3e7d09ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('type_chat', sa.String(length=100), nullable=False),
    sa.Column('invite_link', sa.String(length=255), nullable=True),
    sa.Column('start_count_subs', sa.BigInteger(), nullable=True),
    sa.Column('join_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('join_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='unique_subscriber_per_channel')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('join_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_vizit', sa.DateTime(timezone=True), nullable=False),
    sa.Column('leave_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('channel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('subscribers')
    op.drop_table('channels')
    # ### end Alembic commands ###
