"""тест2

Revision ID: 5b0c53fd80a7
Revises: b5d54518abd2
Create Date: 2025-05-10 20:20:56.641735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b0c53fd80a7"
down_revision: Union[str, None] = "b5d54518abd2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscribers", sa.Column("user1", sa.BigInteger(), nullable=False)
    )
    op.add_column(
        "subscribers", sa.Column("user2", sa.String(), nullable=False)
    )
    op.add_column(
        "subscribers", sa.Column("user3", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscribers", "user3")
    op.drop_column("subscribers", "user2")
    op.drop_column("subscribers", "user1")
    # ### end Alembic commands ###
