"""тест1

Revision ID: b5d54518abd2
Revises: 4ffd3e7d09ee
Create Date: 2025-05-10 20:10:16.366523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d54518abd2'
down_revision: Union[str, None] = '4ffd3e7d09ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('is_startsubs', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'is_startsubs')
    # ### end Alembic commands ###
