"""Финальная версия таблиц из прошлого проекта

Revision ID: efb815d7acba
Revises: c988ed9ce08a
Create Date: 2025-05-17 20:04:35.196913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb815d7acba'
down_revision: Union[str, None] = 'c988ed9ce08a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('channels', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('channels', sa.Column('type_chat', sa.String(length=100), nullable=True))
    op.add_column('channels', sa.Column('invite_link', sa.String(length=255), nullable=True))
    op.add_column('channels', sa.Column('join_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('channels', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('channels', sa.Column('disable_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscribers', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('subscribers', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('subscribers', sa.Column('is_bot', sa.Boolean(), nullable=False))
    op.add_column('subscribers', sa.Column('is_self', sa.Boolean(), nullable=False))
    op.add_column('subscribers', sa.Column('is_contact', sa.Boolean(), nullable=False))
    op.add_column('subscribers', sa.Column('is_mutual_contact', sa.Boolean(), nullable=False))
    op.add_column('subscribers', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('subscribers', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('subscribers', sa.Column('is_restricted', sa.Boolean(), nullable=False))
    op.add_column('subscribers', sa.Column('is_scam', sa.Boolean(), nullable=False))
    op.add_column('subscribers', sa.Column('is_fake', sa.Boolean(), nullable=False))
    op.add_column('subscribers', sa.Column('is_support', sa.Boolean(), nullable=False))
    op.add_column('subscribers', sa.Column('is_premium', sa.Boolean(), nullable=False))
    op.add_column('subscribers', sa.Column('status', sa.String(length=100), nullable=True))
    op.add_column('subscribers', sa.Column('last_online_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscribers', sa.Column('next_offline_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscribers', sa.Column('code_language', sa.String(length=255), nullable=True))
    op.add_column('subscribers', sa.Column('emoji_status', sa.String(length=255), nullable=True))
    op.add_column('subscribers', sa.Column('dc_id', sa.BigInteger(), nullable=True))
    op.add_column('subscribers', sa.Column('photo_small_id', sa.String(length=255), nullable=True))
    op.add_column('subscribers', sa.Column('photo_small_id_unique', sa.String(length=255), nullable=True))
    op.add_column('subscribers', sa.Column('restrictions', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('left_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_vizit', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('users', sa.Column('invite_link', sa.String(length=255), nullable=True))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_column('users', 'invite_link')
    op.drop_column('users', 'last_vizit')
    op.drop_column('users', 'left_at')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'username')
    op.drop_column('subscribers', 'restrictions')
    op.drop_column('subscribers', 'photo_small_id_unique')
    op.drop_column('subscribers', 'photo_small_id')
    op.drop_column('subscribers', 'dc_id')
    op.drop_column('subscribers', 'emoji_status')
    op.drop_column('subscribers', 'code_language')
    op.drop_column('subscribers', 'next_offline_date')
    op.drop_column('subscribers', 'last_online_date')
    op.drop_column('subscribers', 'status')
    op.drop_column('subscribers', 'is_premium')
    op.drop_column('subscribers', 'is_support')
    op.drop_column('subscribers', 'is_fake')
    op.drop_column('subscribers', 'is_scam')
    op.drop_column('subscribers', 'is_restricted')
    op.drop_column('subscribers', 'is_verified')
    op.drop_column('subscribers', 'is_deleted')
    op.drop_column('subscribers', 'is_mutual_contact')
    op.drop_column('subscribers', 'is_contact')
    op.drop_column('subscribers', 'is_self')
    op.drop_column('subscribers', 'is_bot')
    op.drop_column('subscribers', 'last_name')
    op.drop_column('subscribers', 'username')
    op.drop_column('channels', 'disable_at')
    op.drop_column('channels', 'is_active')
    op.drop_column('channels', 'join_at')
    op.drop_column('channels', 'invite_link')
    op.drop_column('channels', 'type_chat')
    op.drop_column('channels', 'description')
    op.drop_column('channels', 'username')
    # ### end Alembic commands ###
